# Instructor Action: Lecture

## Picture Prompt

Show students an image with no explanation, and ask them to identify/explain it, and justify their answers. Or ask students to write about it using terms from lecture, or to name the processes and concepts shown. Also works well as group activity. Do not give the “answer” until they have explored all options first.

## Why Do You Think That?

Follow up all student responses (not just the incorrect ones) with a challenge to explain their thinking, which trains students over time to think in discipline-appropriate ways.

## Think Break

Ask a rhetorical question, and then allow 20 seconds for students to think about the problem before you go on to explain. This technique encourages students to take part in the problem-solving process even when discussion isn't feasible. Having students write something down (while you write an answer also) helps assure that they will in fact work on the problem.

## Updating Notes

Take a break for 2-3 minutes to allow students to compare their class notes so far with other students, fill in gaps, and develop joint questions.

## Cliffhanger Lecturing

Rather than making each topic fit neatly within one day’s class period, intentionally structure topics to end three-fourths of the way through the time, leaving one quarter of the time to start the next module/topic. This generates an automatic bridge between sessions and better meets learning science principles of the spacing effect and interleaving topics.

## Choral Response

Ask a one-word answer to the class at large; volume of answer will suggest degree of comprehension. Very useful to “drill” new vocabulary words into students.

## Word Cloud Guessing

Before you introduce a new concept to students, show them a word cloud on that topic, using an online generator (Wordle, Taxedo, or Tagul) to paste a paragraph or longer of related text, and challenge students to guess what the topic was.

## Instructor Storytelling

Instructor illustrates a concept, idea, or principle with a real- life application, model, or case-study.

## Grab a Volunteer

After a minute paper (or better: think pair share) pick one student to stand up, cross the room, and read any other student's answer.

## Socratic Questioning

The instructor replaces lecture by peppering students with questions, always asking the next question in a way that guides the conversation toward a learning outcome (or major Driving Question) that was desired from the beginning. Variation: A group of students writes a series of questions as homework and leads the exercise in class.
Reverse Socratic Questioning

The instructor requires students to ask him/her questions, and the instructor answers in such a way as to goad another question immediately but also drive the next student question in a certain direction.

## Pass the Pointer

Place a complex, intricate, or detailed image on the screen and ask for volunteers to temporarily borrow the laser pointer to identify key features or ask questions about items they don’t understand.

## Turn My Back

Face away from the class, ask for a show of hands for how many people did the reading. After they put hands down, turn around again and ask to hear a report of the percentage. This provides an indication of student preparation for today’s material.

## Empty Outlines

Distribute a partially completed outline of today’s lecture and ask students to fill it in. Useful at start or at end of class.

## Classroom Opinion Polls

Informal hand-raising suffices to test the waters before a controversial subject.

## Discussion Row

Students take turns sitting in a front row that can earn extra credit as individuals when they volunteer to answer questions posed in class; this provides a group that will ALWAYS be prepared and interact with teacher questions.

## Total Physical Response (TPR)

Students either stand or sit to indicate their binary answers, such as True/False, to the instructor’s questions.

## Student Polling

Select some students to travel the room, polling the others on a topic relevant to the course, then report back the results for everyone.

## Self-Assessment of Ways of Learning

Prepare a questionnaire for students that probes what kind of learning style they use, so the course can match visual/aural/tactile learning styles.

## Quote Minus One

Provide a quote relevant to your topic but leave out a crucial word and ask students to guess what it might be: “I cannot forecast to you the action of ______; it is a riddle, wrapped in a mystery, inside an enigma.” This engages them quickly in a topic and makes them feel invested.

## Everyday Ethical Dilemmas

Present an abbreviated case study with an ethical dilemma related to the discipline being studied.

## Polar Opposites

Ask the class to examine two written-out versions of a theory (or corollary, law of nature, etc.), where one is incorrect, such as the opposite or a negation of the other. In deciding which is correct, students will have to examine the problem from all angles.

## Pop Culture

Infuse your lectures, case studies, sample word problems for use during class with current events from the pop culture world. Rather than citing statistics for housing construction, for instance, illustrate the same statistical concept you are teaching by inventing statistics about something students gossip about, like how often a certain pop star appears in public without make-up.

## Make Them Guess

Introduce a new subject by asking an intriguing question, something that few will know the answer to (but should interest all of them). Accept blind guessing for a while before giving the answer to build curiosity.

## Make It Personal

Design class activities (or even essays) to address the real lives of the individual students. Instead of asking for reflections on Down’s Syndrome, ask for personal stories of neurological problems by a family member or anyone they have ever met.

## Read Aloud

Choose a small text (500 words or less) to read aloud, and ask students to pay particular attention during this phase of lecture. A small text read orally in a larger lecture can focus attention.

## Punctuated Lectures

Ask student to perform five steps: listen, stop, reflect, write, give feedback. Students become self-monitoring listeners.

## Word of the Day

Select an important term and highlight it throughout the class session, working it into as many concepts as possible. Challenge students to do the same in their interactive activities.

## Recall, Summarize, Question, Connect, and Comment

This method of starting each session (or each week) has five steps to reinforce the previous session’s material: recall it, summarize it, phrase a remaining question, connect it to the class as a whole, and comment on that class session.

## Background Knowledge Probe

Use questionnaire (multi-choice or short answer) when introducing a new topic.

## Goal Ranking and Matching

Students rank their goals for the class, then instructor combines those with her own list.

## Interest/Knowledge/Skills Checklist

Assesses interest and preparation for the course, and can help adjust teaching agenda.

## Documented Problem Solutions

Keep track of the steps needed to solve specific types of problems. Model a list for students first and then ask them to perform similar steps.

## Provocative Picture

Begin the lecture with a picture meant to provoke discussion or emotion (another option: a cartoon).
