# Instructor Action: Lecture (Small Class Size)

## Pass the Chalk

Provide chalk or a soft toy; whoever has it must answer your next question, and they pass it on to the student of their choice.

## Whiteboard Capture

Using a smartphone, take photographs of the whiteboard at the end of the day and post them to Canvas (labeled by date) for easy student reference.

## Pass the Dart

Like Pass the Chalk, use a real (but safe?) dartboard to decide which student must answer the next question (student names are arranged on the dartboard already).

## Beach Ball Bingo

Write questions or prompts onto all surfaces of a beach ball (or tape them on). When the next student catches the ball, he/she answers one of the questions where fingers are touching the ball.

## Bingo Balls of Doom

Every student is assigned a number; when the faculty member pulls that number from the bingo cage, that student has to answer the next question.

## Town Hall Meeting

Abdicate the front of the room for a student willing to speak out on a controversial subject, and when she is done with her comment, she selects the next speaker from the hands raised.

## The Half Class Lecture

Divide the class in half and provide reading material to one half. Lecture on that same material to the other half of the class. Then, switch the groups and repeat, ending with a recap by pairing up members of opposite groups.

## Tournament

Divide the class into at least two groups and announce a competition for most points on a practice test. Let them study a topic together and then give that quiz, tallying points. After each round, let them study the next topic before quizzing again. The points should be carried over from round to round. The student impulse for competition will focus their engagement onto the material itself.

## Three Part Interview

Pose the following question to the entire class: “What do you think are the three biggest issues related to ____.” Choose the student with the birthday closest to today’s date and have them stand and share their 3 responses to the question for one minute. Move clockwise around the room until all have shared.