# Student Action Individual 

Many of these can be used as partnerwork or groupwork instead; or may escalate to that after some individual effort.

## Mind Dump

Students write for five minutes on last night's reading, and this paper gets collected. The entire chapter's worth of mind dumps are returned as a surprise to help students study for the test.

## One-Minute Papers

Students write for one minute on a specific question (which might be generalized to “what was the most important thing you learned today”). Best used at the end of the class session.

## Backchannel Discussion

While the instructor presents, students use digital devices to engage in a chatroom-style conversation projected alongside the instructor. Students ask questions, make comments, and share relevant resources. The instructor periodically ties the conversation into their presentation.

## Muddiest Point

Like the Minute Paper, but asks for the “most confusing” point instead. Best used at the end of the class session.

## Misconception Check

Discover class’s preconceptions. Useful for starting new chapters.

## Drawing for Understanding

Students illustrate an abstract concept or idea. Comparing drawings around the room can clear up misconceptions.

## Snowballs

Ball up several blank pieces of paper and throw them around the room. Each time a “snowball” lands on a desk, the recipient must write three takeaways from today’s (or yesterday’s) class, taking care not to duplicate other ideas already on this paper, and then throw it onward. After nine ideas are on each page, pause for students to debrief the pages in groups.

## Focused Listing

Students list several ideas related to the main focus point (example: list all the possible causes of the Civil War). Helpful for starting new topics, such as a brainstorm.

## Focused Listing by Letter

Same as “focused listing” but students are restricted to start each term in their list with just one letter announced by the teacher (ie, “all answers must start with an S”).

## Gallery Walk

Stations or displays are spread across the room, and students go around to each station individually or in groups, completing a task or responding to a prompt at each station.

## Activity Gallery Walk

Stations around the room have activities, rather than materials to read/debrief/discuss, each of which take a significant amount of time to work through. Students usually choose to work on problems they have the most trouble with, and skip ones they already understand.

## Turn Taking Reading

Instead of the instructor reading a paragraph on screen (or leaving silence for students to do it), instruct them we will sit in silence until someone is moved to read ONE sentence, then someone else anyone will start the next sentence. Adds “good” tension and raises energy.

## Haiku

Students write a haiku (a three-line poem: 5-syllables, then 7, then 5) on a given topic or concept, and then share it with others.

## Whip Around

Give students a few seconds to think of their answer to a question, then move around the whole class with each one giving their (one word?) answer. Disallow repeat answers (but do allow a “pass” if necessary).

## Rotating Chair

One volunteer “takes the microphone” at a time, then calls on the next volunteer. Each subsequent speaker must summarize the previous one’s points (or, if desired, ALL the speakers thus far) before adding original ideas.

## Media Break

Designate a two minute break in the middle of class for students to check their electronic devices, with the understanding they won’t use them otherwise in the entire class period.

## Photo Homework

Students are assigned to use a smartphone to snap a picture of something at home (or out in the city) that captures a specific concept from the class, as assigned by the teacher.

## Board of Artwork

Post publicly the collected drawings / abstract concepts that students turned in for a previous activity and create an opportunity for discussion and debrief.

## Time Traveler

Students video themselves at the start of the semester answering questions similar to the eventual final exam, then critique it near the end of the term.

## Circle the Questions

Pre-make a handout that has a few dozen likely student questions (make them specific) on your topic for that day and ask students to circle the ones they don’t know the answers to, then turn in the paper.

## Ask the Winner

Ask students to silently solve a problem on the board. After revealing the answer, instruct those who got it right to raise their hands (and keep them raised); then, all other students are to talk to someone with a raised hand to better understand the question and how to solve it next time.

## What’s the Principle

After recognizing the problem, students assess what principle to apply in order to solve it. Helps focus on problem TYPES rather than individual specific problems. Principle(s) should be listed out.

## Video Selfie

Ask students to make a video of themselves performing the homework (or lab), as they will take it more seriously and be more likely to avoid mistakes.

## Infographic

Students use online services (visual.ly, infogr.am) to create an infographic that combines flowchart logic and visual presentation

## Bookmark Notes

Distribute full-length paper to be used as a bookmark for the current chapter. On it, record prompts and other “reading questions”, and require students to record their notes, observations, and objections while reading onto these bookmarks for collection and discussion in class.

## True or False?

Distribute index cards (one to each student) on which is written a statement. Half of the cards will contain statements that are true, half false. Students decide if theirs is one of the true statements or not, using whatever means they desire. Variation: designate half the room a space for those who think their statements are true, and the other half for false.

## “Real-World”

Have students discuss in class how a topic or concept relates to a real- world application or product. Then have students write about this topic for homework. Variation: ask them to record their answer on index cards.

## Concept Mapping

Students write keywords onto sticky notes and then organize them into a flowchart. Could be less structured: students simply draw the connections they make between concepts.

## Advice Letter

Students write a letter of advice to future students on how to be successful students in that course.

## Tabloid Titles

Ask students to write a tabloid-style headline that would illustrate the concept currently being discussed. Share and choose the best.

## Bumper Stickers

Ask students to write a slogan-like bumper sticker to illustrate a particular concept from lecture. Variation: can be used to ask them to sum up the entire course in one sentence.

## One-Sentence Summary

Summarize the topic into one sentence that incorporates all of who/what/when/where/why/how creatively.

## Directed Paraphrasing

Students asked to paraphrase part of a lesson for a specific audience (and a specific purpose).

## Word Journal

First, summarize the entire topic on paper with a single word. Then use a paragraph to explain your word choice.

## Truth Statements

Either to introduce a topic or check comprehension, ask individuals to list out “It is true that...” statements on the topic being discussed. The ensuing discussion might illustrate how ambiguous knowledge is sometimes.

## Objective Check

Students write a brief essay in which they evaluate to what extent their work fulfills an assignment’s objectives.

## Opposites

Instructor lists out one or more concepts, for which students must come up with an antonym, and then defend their choice.

## Student Storytelling

Students are given assignments that make use of a given concept in relation to something that seems personally relevant (such as requiring the topic to be someone in their family).

## Application to Major

During last 15 minutes of class, ask students to write a short article about how the point applies to their major.

## Pro and Con Grid

Students list out the pros and cons for a given subject.

## Harvesting

After an experience/activity in class, ask students to reflect on “what” they learned, “so what” (why is it important and what are the implications), and “now what” (how to apply it or do things differently).

## Chain Notes

Instructor pre-distributes index cards and passes around an envelope, on which is written a question relating to the learning environment (i.e., are the group discussions useful?) Students write a very brief answer, drop in their own card, and pass the envelope to the next student.

## Focused Autobiographical Sketches

Focuses on a single successful learning experience, one relevant to the current course.

## Course-Related Self-Confidence Surveys

Simple questions that measure how self-confident students are when it comes to a specific skill. Once they become aware they can do it, they focus on it more.

## Profiles of Admirable Individuals

Students write a brief profile of an individual in a field related to the course. Students assess their own values and learn best practices for this field.

## Memory Matrix

Identify a key taxonomy and then design a grid that represents those interrelationships. Keep it simple at first. Avoid trivial or ambiguous relationships, which tend to backfire by focusing students on superficial kinds of learning. Although probably most useful in introductory courses, this technique can also be used to help develop basic study skills for students who plan to continue in the field

## Categorizing Grid

Hand out rectangles divided into cells and a jumbled listing of terms that need to be categorized by row and column.

## Defining Features Matrix

Hand out a simple table where students decide if a defining feature is PRESENT or ABSENT. For instance, they might have to read through several descriptions of theories and decide if each refers to behaviorist or constructivist models of learning.

## What/How/Why Outlines

Write brief notes answering the what / how / why questions when analyzing a message or text.

## Approximate Analogies

Students provide the second half of an analogy (A is to B as X is to Y).

## Problem Recognition Tasks

Offer case studies with different types of problems and ask students to identify the TYPE of problem (which is different from solving it)

## Switch it up!

Ask students to work on one problem for a few minutes and intentionally move to a second problem without debriefing the first one, then solve the second one and only then return to the first one for more work. A carefully chosen second problem can shed light on the first problem, but this also works well if the problems are not directly related to each other.

## Reading Rating Sheets

Students fill out a ratings sheet on the course readings, on how clear, useful, and interesting it was.

## Assignment Assessments

Students give feedback on their homework assignments, and evaluate them as learning tools.

## Exam Evaluations

Students explain what they are learning from exams, and evaluate the fairness, usefulness, and quality of tests.

## Group-Work Evaluations

Questionnaires asking how effective groupwork has been in the class.

## Teacher-Designed Feedback Forms

Rather than use standardized evaluation forms, teachers create ones tailored for their needs and their classes. Especially useful midway through the term.

## Writing Fables

Students write an animal fable (or at least sketch its outline) that will lead to a one-sentence moral matching the current concept discussed in class. May be done verbally instead.