# Student Action: Pairs

## Think-Pair-Share

Students share and compare possible answers to a question with a partner before addressing the larger class.

## Pair-Share-Repeat

After a pair-share experience, ask students to find a new partner and debrief the wisdom of the old partnership to this new partner.

## Teach-OK

The instructor briefly explains a concept. The teacher then says “teach!”, and the students respond “OK!”. Students then form pairs and take turns re-teaching the concept to one another.

## Wisdom of Another

After any individual brainstorm or creative activity, partner students up to share their results. Then, call for volunteers of students who found their partner’s work to be interesting or exemplary. Students are sometimes more willing to share in plenary the work of fellow students than their own work.

## Human Flashcards

Students take turns calling out terms they were expected to memorize, and demand an answer from their partner.

## Storytelling Gaps

One partner relay a story that summarizes learning in the chapter so far, but leaves out crucial fine information (such as dates that should have been memorized). The partner listens and records dates silently on paper as the story progresses and then updates the first person.

## Do-Si-Do

Students do partner work first, then sound off by twos. All of the 2’s stand up and find a new partner (the 1’s are seated and raise their hands until a new partner comes), then debrief what was said with the first partner. Variation: Later, all the 1’s come together in a large circle for a group debrief, while the 2’s have their own circle.

## Forced Debate

Students debate in pairs, defending either their preferred position or the opposite of their preferred position. Variation: Half the class takes one position, half the other. The two halves line up, face each other, and debate. Each student may only speak once, so that all students on both sides can engage the issue.

## Optimist/Pessimist

In pairs, students take opposite emotional sides of a conversation. This technique can be applied to case studies and problem solving as well.

## Teacher and Student 

Individually brainstorm the main points of the last homework, then assign roles of teacher and student to pairs. The teacher’s job is to sketch the main points, while the student’s job is to cross off points on his list as they are mentioned, but come up with 2-3 ones missed by the teacher.

## Peer Review Writing Task

To assist students with a writing assignments, encourage them to exchange drafts with a partner. The partner reads the essay and writes a three- paragraph response: the first paragraph outlines the strengths of the essay, the second paragraph discusses the essay’s problems, and the third paragraph is a description of what the partner would focus on in revision, if it were her essay.

## Invented Dialogues

Students weave together real quotes from primary sources, or invent ones to fit the speaker and context.

## My Christmas Gift

Students mentally select one of their recent gifts as related to or emblematic of a concept given in class, and must tell their partners how this gift relates to the concept. The one with a closer connection wins.

## Psychoanalysis

Students get into pairs and interview one another about a recent learning unit. The focus, however, is upon analysis of the material rather than rote memorization. Sample Interview Questions: Can you describe to me the topic that you would like to analyze today? What were your attitudes/beliefs before this topic? How did your attitudes/beliefs change after learning about this topic? How will/have your actions/decisions altered based on your learning of this topic? How have your perceptions of others/events changed?

## Get One, Give One

Students fold a piece of paper in half and write “Give One” on one side and “Get One” on the other side. On the “Give One” side, as them to write four insights from today’s material. Have them stand up and find a partner. Each student shares one idea from their “Give One” side of the paper and writes down one idea on the “Get One” side of the paper. Find a new partner until your “Get One” side of paper is full of new ideas!
