# Student Action: Groups

## Jigsaw (Group Experts)

Give each group a different topic. Re-mix groups with one planted “expert” on each topic, who now has to teach his new group. Also useful to have them teach each other sections of the syllabus on the first day.

## Single Jigsaw

Divide the class in two. After speed sharing or similar activity, each person finds a partner from the other group to do a lengthy debrief.

## Carousel Brainstorming

Everyone in the group writes out a problem statement, then passes the paper to the student on the left. This student records one possible answer or idea. At the signal, all papers shift to the left again, until the entire circle has seen each paper and they return to their original owners.

## World Café

Small groups tackle the same driving question; plenary debrief, then everyone except table hosts find a new table (new groups) for a second discussion question. The host leads discussions and draws ideas between rounds, taking notes for sticky wall posters.

## Mystery Numbers

Every student in the group gets a unique number (such as 1-5), but the teacher doesn’t announce until AFTER the discussion period which person (number) is going to report back to the larger class. This will convince everyone to participate fully.

## Assembling Strips 

Give each group an envelope with cut-out strips that assemble into a timeline, a plan of action, etc. Option: include "too many" so groups have to be selective.

## Empty Table

Hand each group a blank table with headers in place for rows and columns, but interior cells are blank until the group fills them in (example: column headers could be different authors such as Shakespeare, Goethe, etc, and row headers could be genres such as poems, novels, essays, etc)

## Group Symbols

Ask students in groups to come up with a summary (or thesis statement) of the reading on a scrap of paper, then add a handwritten symbol or stick figure drawing to identify the scrap. Pass to the right, pausing at each group, until everyone has seen everything. Using the symbols as identification, each group decide which two statements are the best, and record the votes on the board.

## With a Creative Twist

When assigning group presentations of different topics, each group also gets a 'twist' at random (such as must deliver some lines as limericks, must present part as karaoke song, etc)

## Gap Exercise

Students freewrite for five minutes on "what is" versus "what should be" (or some other gap in your field) then debrief in threes. When it's a student's turn, she first summarizes her freewrite and then is silent and listens as the other two ask questions only (give no advice, do not swap stories), then work around the group every couple of minutes.

## Brain Drain

Divide students into groups of 5 or 6. Hand out an empty grid of six rows and three columns to every student. Provide a prompt or task at the top to brainstorm. Each person brainstorms possible answers in row one. After three minutes, rotate papers clockwise and work on row 2 (but do not repeat any answers from row 1). Continue until sheet is filled in, then debrief to find the best answers.

## Interactive Lit Review

Give a different snippet of reading to each group in the room and a specific task (such as “map ideas onto this larger set of principles you see on the screen”); capture bullets onto the board, then follow with a Gallery Walk to lead to more debrief.

## Balloon Pop

Give each group an inflated balloon with the task/problem trapped inside on a piece of paper. At the signal, all groups pop their balloons. Injects fun, noise, and energy to a group assignment.

## Things You Know

Give an envelope to every student. Inside are cut-up strips of paper with the topics/principles they should know about already. They divide into two piles: things they know well, and things they need help with. Then they debrief with nearby students on things any of them need help with.

## Board Rotation

Assign groups of students to each of the boards you have set up in the room (four or more works best), and assign one topic/question per board. After each group writes an answer, they rotate to the next board and write their answer below the first, and so on around the room. Variations: pass around flipchart paper with the same task, or use the idea of “table topics” where the topic stays at one table while students rotate. Consider using Google Docs for common note-taking at each table.

## Make it a Story

Encourage students to submit their group projects as a comic or story created online (bubblr, StripCreator, StoryJumper, or Storify)

## Creating Categories

In groups, students freewrite a position statement about your topic. Then they sort quotes/claims on strips of paper that you handed out, by creating categories as they go. Finally, they add their position statements on (or between) categories. The exercise should point out "families" of assumptions about a topic.

## Pass the Problem

Divide students into groups. Give the first group a case or a problem and ask them to identify (and write down) the first step in solving the problem or analyzing the case (3 minutes). Pass the problem on to the next group and have them identify the next step. Continue until all groups have contributed.

## Pick the Winner

Divide the class into groups and have all groups work on the same problem and record an answer/strategy on paper. Then, ask groups to switch with a nearby group, and evaluate their answer. After a few minutes, allow each set of groups to merge and ask them to select the better answer from the two choices, which will be presented to the class as a whole.

## Layered Cake Discussion

Every table/group works on the same task for a few minutes, then there’s a plenary debrief for the whole class, and finally repeat with a new topic to be discussed in the groups.

## Claymation Videos

Instead of a written paper or essay, the deliverable of a group project can be a video uploaded to YouTube created by the group using modeling clay and a stop-motion video app on their smartphones.

## Student Learning Communities

Like faculty learning communities, these communities of practice are meant to invest the participants with ownership and a focus on sharing and joint discovery. Can be structured or unstructured.

## Lecture Reaction

Divide the class into four groups after a lecture: questioners (must ask two questions related to the material), example givers (provide applications), divergent thinkers (must disagree with some points of the lecture), and agreers (explain which points they agreed with or found helpful). After discussion, brief the whole class.

## Movie Application

In groups, students discuss examples of movies that made use of a concept or event discussed in class, trying to identify at least one way the movie-makers got it right, and one way they got it wrong.

## Student Pictures

Ask students to bring their own pictures from home to illustrate a specific concept to their working groups.

## Definitions and Applications

In groups, students provide definitions, associations, and applications of concepts discussed in lecture.

## TV Commercial

In groups, students create a 30-second TV commercial for the subject currently being discussed in class. Variation: ask them to act out their commercials.

## Blender

Students silently write a definition or brainstorm an idea for several minutes on paper. Then they form into groups, and two of them read their ideas and integrate elements from each. A third student reads his, and again integration occurs with the previous two, until finally everyone in the group has been integrated (or has attempted integration).

## Human Tableau or Class Modeling

Groups create living scenes (also of inanimate objects) which relate to the classroom concepts or discussions.

## Build From Restricted Components

Provide limited resources (or a discrete list of ideas that must be used) and either literally or figuratively dump them on the table, asking students in groups to construct a solution using only these things (note: may be familiar from the Apollo 13 movie). If possible, provide red herrings, and ask students to construct a solution using the minimum amount of items possible.

## Ranking Alternatives

Teacher gives a situation, everyone thinks up as many alternative courses of action (or explanations of the situation) as possible. Compile list. In groups, now rank them by preference.

## Simulation

Place the class into a long-term simulation (like as a business) to enable Problem-Based Learning (PBL).

## Group Instructional Feedback Technique

Someone other than the teacher polls groups on what works, what doesn’t, and how to fix it, then reports them to the teacher.

## Classroom Assessment Quality Circles

A small group of students forms a “committee” on the quality of teaching and learning, which meets regularly and includes the instructor.

## Audio and Videotaped Protocols

Taping students while they are solving problems assesses the learner’s awareness of his own thinking.

## Imaginary Show and Tell

Students pretend they have brought an object relevant to current discussion, and “display” it to the class while talking about its properties.

## Six Degrees of “RNA Transcription Errors”

Like the parlor game “Six Degrees of Kevin Bacon” (in which actors are linked by joint projects), you provide groups with a conceptual start point and challenge them to leap to a given concept in six moves or fewer. One student judge in each group determines if each leap is fair and records the nature of the leaps for reporting back to the class.

## Sticky Note Discussions

Divide students into cooperative groups and have them read individually. Ask them to use sticky notes to mark places that they want to talk about in the text. Then direct them to reread as a group and discuss the parts they have marked.

## Pinwheel Discussions

Students are divided into groups. All but one of the groups are assigned to specific topics or positions, while the fourth group is designated as the “provocateur” group. Each group chooses a speaker, and speakers sit facing each other with their other group members seated fanned out behind them (the overhead view of this configuration looks like a pinwheel). The speakers discuss their assigned positions (or provoke further discussion, if in the “provocateur” group), and every few minutes, new speakers rotate in and continue the discussion.

## Snowball Discussions

Students form pairs and respond to a discussion question posed by the instructor. After a few moments, pairs join together to form groups of 4 and share their ideas. Groups of 4 then join to create groups of 8, and so forth until the entire class is engaged in discussion.