# Testing Strategies

## Bark/Bite Grading

Collect multiple assessments (such as multiple at-home essay questions at a test) but tell students they will only be graded on ONE of them blindly

this will maximize their preparation but minimize the grading workload.

## Redacted Test

A few days before the chapter test, deliver to students the ACTUAL test questions to be used, only with key information blacked out (example: “The BLANK law of thermodynamics states that BLANK”). Do not include the multiple choice answers at this stage, which forces students to generate their own effectively tuned study guides.

## Test Variants

Testing in large lecture classes with cramped seating can lead to cheating. Creating two versions of the test, and forcing students to alternate while seated in the row, can reduce cheating. Rather than completely different questions, it may be more fair simply to scramble the order in which the (same) questions are delivered across variants.

## Bluffed Test Variants

Simply handing out the paper test photocopied onto two different colors, even if using the same questions and the same order, can reduce student cheating.