# Twitter

## Report from the Field

Students use smart phones to record their observations while witnessing an event/location related to the course of study, capturing more honest and spontaneous reactions

## Twitter Clicker Alternative

In large classes, a hashtag can amalgamate all posts by your students in one place, giving them a free-response place to provide feedback or guess at a right answer. Also useful for brainstorming.

## Backchannel Conversations in Large Classes

unlike a whispered conversation, a Twitter conversation (searchable by agreed-upon hashtag) becomes a group discussion. Students may also help out other students who missed a brief detail during the lecture.

## Follow an Expert

Luminaries in many disciplines, as well as companies and governmental agencies, often publish a Twitter feed. Reading such updates provides a way to stay current.

## Tweeted Announcements

Instead of Blackboard, use Twitter to send out announcements like cancelled classes.

## Twitter Pictures and URLs

Twitpic and other services allows for photo upload to twitter; bit.ly and other “link shorteners” allow for pasting long URLs as short ones.

## Student Summaries

Make one student the “leader” for tweets; she posts the top five important concepts from each session to twitter (one at a time); other students follow her feed and RT for discussion/disagreements

## Historical Tweets

Students roleplay as historical figures (Lincoln, Napoleon) or fictional characters (Hamlet, Three Little Pigs) and tweet as if in specific contexts.

## Quick Contact

Since sharing cell phone numbers is risky, instructors may wish to let students follow them on Twitter and send Direct Messages that way.

## Community-Building

A Twitter group for your specific class creates inclusiveness and belonging.

## Twitter Projects

Tweetworks and other apps can enable student groups to communicate with each other more easily.

## Brainstorm

Small Twitter assignments can yield unexpected brainstorming by students, since it’s happening “away” from the LMS.

## Twitter Poll

PollDaddy and other apps enable Twitter to gather interest, information, attitudes, and guesses.

## Post Links

News stories and other websites can be linked via Twitter (services such as bit.ly will shorten URLs).