# Creating Groups

## Quick Division

Divide your class into two roughly equal segments for simultaneous, parallel tasks by invoking their date of birth: “if your birthday falls on an odd-numbered day, do task X...if your birthday is even, do task Y.” Other variations include males and females, months of birth, odd or even inches in their height (5’10” vs 5’11”).

## Question and Answer Cards

Make index cards for every student in the class; half with questions about class content; half with the right answers. Shuffle the cards and have students find their appropriate partner by comparing questions and answers on their own cards.

## Telescoping Images

When you need the class to form new groups, craft sets of index cards that will be grouped together by theme, and randomly pass them out for students to seek the other members of their new groups. Example: one set of four index cards has pictures of Europe on a map, then France, then the Eiffel Tower, then a person wearing a beret (thematically, the images “telescope” from far away to close up, and the students must find others in their particular set of telescoping images).

## Speed Sharing

Students write definitions, concepts, quiz questions, etc. on index cards and form two concentric circles, facing each other. For thirty seconds (or 60), they share their knowledge with the person opposite them. Then, the outer circle “rotates” so that everyone has a new partner, and the sharing is repeated. This can be done until each student has completed the circuit.

## Trio Rotation

Group students into threes, and arrange the groups into a large circle. Each team of three works on a problem. Then, each team assigns a 1, 2, and 3 number to each person. The 1’s stay put, but the 2’s rotate clockwise and the 3’s rotate counterclockwise. Newly formed teams then work on a new problem.

## Go to Your Post

Tape a sign onto opposite sides of the walls with different preferences (different authors, skills, a specific kind of problem to solve, different values) and let students self-select their working group

## Four Corners

Put up a different topic in each corner of the room and ask students to pick one, write their ideas about it down, then head to “their” corner and discuss opinions with others who also chose this topic.

## Deck of Cards

Use playing cards to form groups by suit (clubs, hearts, etc), by card (kinds, jacks), or by number. You can pre-assign roles by card.

## Everyone Point!

On a count of three, everyone point to someone in the group. Winner gets to decide who does the debrief to the plenary class.
