# Icebreakers

## Building a Company

In groups, students catalog their various strengths, talents, and skills onto a single sheet. Then, they invent a company/business that makes use of at least one item from everyone in the group. Share with the larger group.

## Something in Common

Place students in pairs and tell them to share with each other until they figure out something they both have in common (even though it’s just a bluff); then ask each partnership to share the common item with the room at large.

## Describe in Three Words

Ask students to learn about their partner, then use only three words in the plenary debrief to describe that person.

## Introduce Your Partner’s Non-Obvious Trait

Students partner up and are tasked with learning one thing about the other person that is not obvious by looking at them. Then, they introduce their partner to the larger class. Instructors can use this time to record a crude seating chart of the students and begin to learn their names.

## Scrapbook Selection

Put students in groups and give each group a big pile of printed photos (best if laminated

maybe different shapes/sizes?) Ask them to choose one as a group that epitomizes their reaction/definition of the topic being discussed, and explain why.

## Brush with Fame

Students relate their closest encounter with someone famous, even if it has to be a story about something that happened to a friend or relative.

## Name Game

Students form circles in groups of 8-10 and one at a time state their name with an alliterative action: “I’m Jumping James!” Optimally, they should perform the action as well. They proceed around the circle, stating names and performing the actions, adding names one at a time, until the last person in the circle will have to say everyone’s name and perform all the actions.

## Human Bingo

Students become acquainted at the start of a semester by performing a scavenger hunt you design as a handout: “find someone who dislikes carrots, someone who owns a German car, someone who has read a book about submarines, etc.”

## Line Dance

Students line up according to their level of agreement on a controversial subject: strong agreement on one side, strong disagreement on the other.

## Two Truths and a Lie

Go around the room and ask each student to relate two true statements and one falsehood about themselves, without giving away which is false.

## Name Tag Trio

Color code name tags and ask people to form groups of three made up of people with nametags of the same color, then introduce themselves.

## Sketch Intro

Ask participants to draw a picture, using no letters, that captures a key facet of their experience, philosophy, or personality.

## Speed Skating

Like the Olympic sport that moves in a circle rapidly, line up students in a circle and step forward one at a time to say a quick personal statement (I am Belgian, I am allergic to peanuts, I love classical music) and then step back into position.

## Word Association Cloud

Collect secret-ballot responses to a word association prompt related to your topic, and paste them into a word-cloud generator to create an image that shows which words were used the most.

## Answer Any Three

Write 5 questions on the board and ask students to stand (or pair off) and answer any 3 of the 5 questions posed. Some sample questions might include: “I have always wanted to......, The person I most admire is..., The two most important job responsibilities I have are ________ and ________., I’m a sucker for..., One reason why I entered my field is..., Something few people know about me is...” Content-related questions may also be used to review material being presented.

## Family Name Game

To help students (and you!) get to know students’ names, ask them to share some history about their name including: 1) who named them, 2) how was the decision for their name made, 3) are they a namesake and do they know that person, 4) do they like their name, 5) have they ever gone by a different name, 6) do they have a nickname, etc.

## What’s in a Name?

Pair students up and allow them to interview one another about their first and middle names, noting any cultural uniqueness. Then have each student in the dyad introduce their partner to the rest of the class sharing what they learned about their partner’s name(s).

## Line Up

Ask students to arrange themselves in a line according to measure of some characteristic (i.e., height, age, birthdate, level of athleticism, etc.). To add a twist, ask students to complete this task without talking.

## Wheel in a Wheel

Ask half of the class form a circle facing outward. Then have the other half of the class form a circle around those students, facing inward, so that they are facing one of the students in the inner circle. The inner circle remains seated throughout the exercise, while the outer circle rotates to the right, one person at a time. With each new pairing you provide a discussion topic/question that will help the students get to know one another. Make sure both partners have time to share. Some example topics include: What do you consider to be one of your greatest accomplishments in life? What person has most affected your life in a positive way? What are the best aspects of your personality and why?

## Scavenger Hunt

Ask students to circulate around the room and locate classmates who fit in certain categories (i.e., only children, lived abroad, bi- or multi-lingual, same major, etc. You can also include statements that revolve around class content.

## Course Expectation Exercise

Write the name of your course on the blackboard. Ask students to individually write down three expectations they have for you or for the course. Then put students into small groups and tell them they must reach consensus regarding their group’s top 3-5 expectations. Then allow groups to report back to the whole class.