# Games (Useful for Review)

## Crossword Puzzle

Create a crossword puzzle as a handout for students to review terms, definitions, or concepts before a test. Some online websites will automate the puzzle creation.

## Jeopardy

Play jeopardy like the TV show with your students. Requires a fair amount of preparation (see quizboxes.com for a simpler way). Can be used also for icebreakers (such as finding out what participants already know about your subject, your university, etc).

## Bingo

Fill out various answers onto bingo cards (each with different words and ordering), then have students cross off each as the definition is read verbally. The first with a whole row or column wins.

## Pictionary

For important concepts and especially terms, have students play pictionary: one draws images only, the rest must guess the term.

## Super-Password

Also for concepts and terms; one student tries to get his partner to say the key term by circumlocution, and cannot say any of the “forbidden words” on a card prepared ahead of time.

## Guess the Password

The instructor reveals a list of words (esp. nouns) one at a time and at each point, ask students to guess what key term they are related to. The hints become increasingly specific to make the answer more clear.

## Twenty Questions

Assign a person, theory, concept, event, etc to individual students and have the partner ask yes/no questions to guess what the concept is. Also works on a plenary level, with one student fielding the questions from the whole class.

## Hollywood Squares

Choose students to sit as “celebrities” at the front of the class. Variation: allow the celebrities to use books and notes in deciding how to help the contestants.

## Scrabble

Use the chapter (or course) title as the pool of letters from which to make words (e.g., mitochondrialdna) and allow teams to brainstorm as many words as possible from that list, but all words must be relevant to this test. Variation: actually play scrabble on boards afterward.

## Who am I?

Tape a term or name on the back of each student, out of view. Each student then wanders about the room, posing yes/no questions to the other students in an effort to guess the term on his own back.

## Ticket out the Door

At the end of class, ask students to summarize the lecture today, or provide one new personal significant learning outcome (in 3-5 sentences), and give their response to the professor for their ticket out of the door.