# Role-Play

## Role-Playing

Assign roles for a concept, students research their parts at home, and they act it out in class. Observers critique and ask questions. Can be done with one student or multiple students participating in the role-play.

## Role Reversal

Teacher role-plays as the student, asking questions about the content. The students are collectively the teacher, and must answer the questions. Works well as test review/prep.

## Jury Trial

Divide the class into various roles (including witnesses, jury, judge, lawyers, defendant, prosecution, audience) to deliberate on a controversial subject.

## Press Conference

Ask students to role-play as investigative reporters asking questions of you, the expert on the topic. They should seek a point of contradiction or inadequate evidence, hounding you in the process with follow-up questions to all your replies. Variation: can be done as group activity, with students first brainstorming questions to ask.

## Press Conference (Guest Speaker)

Invite a guest speaker and run the class like a press conference, with a few prepared remarks and then fielding questions from the audience.

## Analytic Memo

Write a one-page analysis of an issue, roleplaying as an employer or client.