# Student Presentations

## Fishbowl

A student unpacks her ideas and thoughts on a topic in front of others, who take notes and then write a response. Avoid asking questions. Variation: Two students have a discussion in front of the class, while others take notes and write a response.

## Forced Rhyming

As students provide individual elements of a group presentation, they can be asked to take on artificial limitations to engage their creativity. One member must rhyme each line in couplets, for instance, or another must speak only in nouns.

## Impromptu Speeches

Students generate keywords, drop them into a hat, and self- choose presenters to speak for 30 seconds on each topic.

## Anonymous Peer Feedback

For student presentations or group projects, encourage frank feedback from the observing students by asking them to rip up a page into quarters and dedicating comments to each presenter. Multiple variations are possible in “forcing” particular types of comments (i.e., require two compliments and two instances of constructive feedback). Then, ask students to create a pile of comments for Student X, another pile for Student Y, and so on.

## PowerPoint Presentations

For those teaching in computer-mediated environments, put students into groups of three or four students. Students focus their attention on a chapter or article and present this material to the class using PowerPoint. Have groups conference with you beforehand to outline their presentation strategy and ensure coverage of the material.

## Shower Boards

Purchase a slab of shower board from a home improvement store for under $20 and have them cut it into four parts. Use these four boards as whiteboards in student groups; they bring the boards to the front to offer their presentations.