# Brainstorming

## Group Concept Mapping

Start with large posterboards on tables around the room, each with only a central node on it. Participants move around the room, adding sub- nodes to each poster until they are full.

## Affinity Grouping

Each student writes one idea per sticky note, making their own pile. Then, student place the notes onto the whiteboard, attempting to group similar ideas near each other.

## Round Robin

Have groups silently list top 3 answers to a problem/question. Allow all groups to present one idea in a round robin format until all groups have exhausted their lists. Scribe all answers and then discuss how to reduce/re-categorize answers. Have groups vote on top three, provide results, discuss, and vote again.

## Brainstorming on the Board

Students call out concepts and terms related to a topic about to be introduced; the instructor writes them on the board. If possible, group them into categories as you record the responses. Works to gauge pre-existing knowledge and focus attention on the subject.

## Brainstorming Tree

While brainstorming on the board, circle the major concepts and perform sub-brainstorms on those specific words; the result will look like a tree blooming outward.

## Brainstorming in a Circle

Group students to discuss an issue together, and then spend a few minutes jotting down individual notes. One person starts a brainstorming list and passes it to the student to the right, who then adds to the list and passes it along again.

## Chalk Talk

Ask students to go to multiple boards around the room to brainstorm answers to a prompt/assignment, but disallow all talking. Can also be done in groups.