# Online Interaction

## Online Chat (All-Day)

For classes meeting at least partially in an online environment, instructors can simulate the benefits gained by a chat-room discussion (more participation from reserved instructors) without requiring everyone to meet in a chat room for a specific length of time. The day begins with a post from the instructor in a discussion board forum. Students respond to the prompt, and continue to check back all day, reading their peers’ posts and responding multiple times throughout the day to extend discussion.

## Online Chat (Quick)

To gauge a quick response to a topic or reading assignment, post a question, and then allow students to chat in a synchronous environment for the next 10 minutes on the topic. A quick examination of the chat transcript will reveal a multitude of opinions and directions for further discussion. In online environments, many students can “talk” at once, with less chaotic and more productive results than in a face-to-face environment.

## Online Evaluation

For those teaching in online environments, schedule a time which students can log on anonymously and provide feedback about the course and your teaching. Understand, however, that anonymity online sometimes breeds a more aggressive response than anonymity in print.

## Pre-Class Writing

A few days before your computer-mediated class begins, have students respond in an asynchronous environment to a prompt about this week’s topic. Each student should post their response and at least one question for further discussion. During the face-to-face meeting, the instructor can address some of these questions or areas not addressed in the asynchronous forum.

## E-Mail Feedback

Instructor poses questions about his teaching via e-mail; students reply anonymously.