# Credits

Kevin Yee | drkevinyee@gmail.com | Last updated 3/10/2019
Creative Commons [BY-NC-SA-OK](https://creativecommons.org/licenses/by-nc-sa/4.0/) to use and remix if non-commercial, must credit me and use same CC license. (No need to email for permission as long as this footer is included in your copy).

Many individuals have assisted over the years by contributing ideas from their own teaching practices. They are listed below in alphabetical order:

* Melody Bowdon
* Oana Cimpean
* Tace Crouse
* Kenyon Daniel
* Sara Friedman
* Gail Grabowsky
* Jace Hargis
* Amanda Helip-Wooley
* Vicki Lavendol
* Eric Main
* Emad Mansour
* Lianna McGowan
* Sommer Mitchell
* Alison Morrison-Shetlar
* Christina Partin
* Kingsley Reeves
* Kenyatta Rivers
* Erin Saitta
* Anna Turner
* Nicole West

The ebook version is maintained by [Sharon Klinkenberg](https://www.linkedin.com/in/sharonklinkenberg). Any issues or suggestions can be directed at him. Or if you are bold, you can even fork the repository and edit the document through [github](ShKlinkenberg/Interactive_Teaching_Techniques).
